### ISSUE TITLE
chore: `prepare` script implies dependecy to `yarn`

### ISSUE THREAD

**Issue by ModuloM** [moh12594/xstate-store#6]
It seems that, as this repo uses `yarn` binary in `prepare` script, it forces CI to install yarn globally in order to install this dependency. As `npm` is always available on a node.js project, would you consider using npm instead?

Source:
https://github.com/moh12594/xstate-store/blob/main/package.json#L22

**Comment by moh12594** [comment]
Hello @ModuloM !

Yes, you're totally right ! feel free to submit a PR !

Thanks a lot !

**Comment by ModuloM** [comment]
Ok great and you are welcome 😃
PR opened https://github.com/moh12594/xstate-store/pull/7
